config/routes.rb
Rails.application.routes.draw do
  
  resources :polls do 
    resources :questions  
  end

  get "newpoll" => "polls#new" , :as => "newpoll"

  root "polls#new"

end

app/models/poll.rb
class Poll < ActiveRecord::Base
	has_many :questions
end

app/models/possible_answer.rb
class PossibleAnswer < ActiveRecord::Base
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :poll
  has_many :possible_answers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

	def new
		@poll = Poll.new	
		@polls = Poll.all
		@questions = Question.all
	end

	def create
		@poll = Poll.new poll_params
		if @poll.save
			flash[:info] = "Congrats! go for a new one"
			redirect_to '/newpoll'
		end
	end

	def edit
		@poll = Poll.find(params[:id])
	end

	def show
		@poll = Poll.find(params[:id])

	end

	def update
		@poll = Poll.find(params[:id])
		if @poll.update_attributes poll_params
			redirect_to "/newpoll"
		end
	end

	def destroy
		Poll.find(params[:id]).destroy
		redirect_to "/newpoll"
	end
private

def poll_params
	params.require(:poll).permit(:title)
end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	before_action :set_poll
	before_action :set_kind_options

	def new
		@question = @poll.questions.build
	5.times {@question.possible_answers.build}
		@questions = Question.all
	end
	def create
		@question = @poll.questions.build question_params
		if @question.save
			redirect_to root_url
		end
	end

	def edit
		@question = Question.find params[:id]
	end

	def show
		@question = Question.find params[:id]
	end

	def update
		@question = Question.find params[:id]
		if @question.update_attributes question_params
			redirect_to root_url
		end
	end

	def destroy
		Question.find(params[:id]).destroy
		redirect_to root_url
	end

	private 

	def question_params
		params.require(:question).permit(:title,:kind,:poll_id)
	end

	def set_poll
		@poll = Poll.find(params[:poll_id])
	end

	def set_kind_options
		@kind_questions = [
			['Open Question','open'],
			['Multiple Choice', 'choice']
		]
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/_nav.html.erb
<ul class="nav nav-pills topical">
  <li class="active">
    <%= link_to "New Poll", "/newpoll" %>
  </li>
  <li><a href="#">Profile</a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PollsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<%= render 'layouts/nav' %>
		<% flash.each do |name, msg| %>
			<%= content_tag :div , msg, class: "alert alert-#{name}" %>
		<% end -%>
	<%= yield %>
</div>
</body>
</html>

app/views/polls/edit.html.erb
<div class="container topical">
	<div class="col-xs-6">
		<%= form_for @poll do |f| -%>
			<div class="form-group">
				<%= f.text_field :title , placeholder: "Title", class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.submit "Update", class: "btn btn-success" %>
			</div>
		<% end -%>
	</div>
</div>

app/views/polls/new.html.erb
<div class="container topical">
	<div class="col-xs-6">
		<%= form_for @poll do |f| -%>
			<div class="form-group">
				<%= f.text_field :title , placeholder: "Title", class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.submit "Create", class: "btn btn-success" %>
			</div>
		<% end -%>
	</div>
</div>

<h1>All Polls</h1>
<ul class="list-group">
	<% @polls.each do |poll| %>
	  <li class="list-group-item">
		    <span class="badge"><%= link_to "show" , poll_path(poll) %></span>
		    <span class="badge"><%= link_to "edit" , edit_poll_path(poll) %></span>
		    <span class="badge"><%= link_to "delete", poll , method: :delete , data: {confirm: "Are you sure about this?"} %></span>
		    <span class="badge"><%= link_to "Add Question" , new_poll_question_path(poll) %></span>
		    <%= poll.title %>
	  </li>
  <% end -%>
</ul>
<h2>All Questions</h2>
<div class="panel panel-default topical">
	<ul>
		<% @questions.each do |question| %>
		<li>
		  <div class="panel-body">
		    <%= question.title %><br>
		    <%= question.kind %><br>
		    <%= question.poll_id %>
		  </div>
		</li>
		<% end -%>
	</ul>
</div>

app/views/polls/show.html.erb
<div class="panel panel-default topical">
  <div class="panel-body">
    <%= @poll.title %>
  </div>
</div>

app/views/questions/edit.html.erb
<div class="container topical">
	<div class="col-xs-6">
		<%= form_for [@poll , @question ] do |f| -%>
			<div class="form-group">
				<%= f.text_field :title , placeholder: "Title", class: "form-control" %>
			</div>
			<div class="form-group">
				<% @kind_questions.each do |option| %>
					<%= f.radio_button :kind, option[1] %>
					<%= option[0] %>
				<% end -%>
			</div>

			<div class="form-group">
				<%= f.submit "Create", class: "btn btn-success" %>
			</div>
		<% end -%>
	</div>
</div>

app/views/questions/new.html.erb
<div class="container topical">
	<div class="col-xs-6">
		<%= form_for [@poll,@question] do |f| -%>
			<div class="form-group">
				<%= f.text_field :title , placeholder: "Title", class: "form-control" %>
			</div>
			<div class="form-group">
				<% @kind_questions.each do |option| %>
					<%= f.radio_button :kind, option[1] %>
					<%= option[0] %>
				<% end -%>
			</div>
			<div class="form-group">
				<%= f.fields_for :possible_answers do |c| %>
					<%= c.text_field :title ,class: "form-control" %>
				<% end -%>
			</div>
			<div class="form-group">
				<%= f.submit "Create", class: "btn btn-success" %>
			</div>
		<% end -%>
	</div>
</div>

<h1>All Questions</h1>
<ul class="list-group">
	<% @questions.each do |question| %>
	  <li class="list-group-item">
		    <span class="badge"><%= link_to "show" , [@poll,question] %></span>
		    <span class="badge"><%= link_to "edit" , edit_poll_question_path(@poll,question) %></span>
		    <span class="badge"><%= link_to "delete", [@poll,question] , method: :delete , data: {confirm: "Are you sure about this?"} %></span>
		    <%= question.title %>
	  </li>
  <% end -%>
</ul>

app/views/questions/show.html.erb
<div class="panel panel-default topical">
  <div class="panel-body">
    <%= @question.title %>
  </div>
</div>